# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0015_auto_20160421_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypedJS',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('blinking_cursor', models.BooleanField(default=True, verbose_name='blinking cursor')),
                ('json_config', models.TextField(blank=True, help_text='The JSON object passed to Typed.js. For more info <a target="_blank" href="https://github.com/mattboldt/typed.js/">click here</a>', null=True, verbose_name='JSON config')),
            ],
            options={
                'verbose_name': 'Typed.js',
                'verbose_name_plural': 'Typed.js',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
